name: CI

on:
  pull_request:
  push:
    branches:
      - trunk

permissions:
  contents: read

jobs:
  linux:
    name: Linux Swift 6.3
    runs-on: ubuntu-latest
    container: swift:6.3.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Swift Version
        run: swift --version

      - name: Test
        run: swift test

  macos:
    name: macOS 26
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Swift Version
        run: swift --version

      - name: Test
        run: swift test
